# Generated by Django 5.1.7 on 2025-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
