# Generated by Django 5.1.7 on 2025-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userdata_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
