# Generated by Django 5.2.6 on 2025-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userdata_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('guest', 'Гость'), ('employee', 'Сотрудник'), ('organization', 'Организация')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Гость'), ('employee', 'Сотрудник'), ('organization', 'Организация')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
