# Generated by Django 5.1.7 on 2025-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_userdata_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('guest', 'Гость'), ('employee', 'Сотрудник'), ('organization', 'Организация')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Гость'), ('employee', 'Сотрудник'), ('organization', 'Организация')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
