# Generated by Django 5.1.7 on 2025-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_session_session_type_userdata_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='payment_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
