# Generated by Django 5.1.7 on 2025-10-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_userdata_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='login',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='auth_app.userdata'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
