# Generated by Django 5.2.6 on 2025-10-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_session_session_type_userdata_balance_and_more'),
        ('auth_app', '0009_userdata_description_userdata_login_and_more'),
    ]

    operations = [
    ]
