# Generated by Django 5.1.7 on 2025-10-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_userdata_stripe_account_id_and_more'),
        ('user_profile', '0002_transaction_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='The employee to whom the tip is intended', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tips', to='auth_app.userdata'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='guest_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
