# Generated by Django 5.2.6 on 2025-10-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_transaction_employee_transaction_guest_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
