"""
Django settings for easy_tips project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY ='django-insecure-=3#i@nq*f17a)@vo)w%%&3e*z^u6_o_zvt90rem*u%(nkfzrd+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'web']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'auth_app',
    'user_profile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auth_app.middleware.RefreshSessionMiddleware'
]

ROOT_URLCONF = 'easy_tips.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'easy_tips.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'easy_tips'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'qwerty123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

FRONTEND_URL = "https://tips.yoursite.com"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'auth_app.authentication.SessionAuthentication',
    ],
}

# Settings for the payment system (stubs)
PAYMENT_SERVICE = {
    'API_KEY': 'your_payment_service_api_key',
    'SECRET_KEY': 'your_secret_key',
    'WEBHOOK_URL': 'http://localhost:8000/api/auth/tips/webhook/',
    'SUCCESS_URL': 'http://localhost:8000/success-page',
    'FAILURE_URL': 'http://localhost:8000/failure-page'
}

# seconds, session lifetime when extended (e.g. 1 hour)
SESSION_COOKIE_AGE = 60 * 60

SESSION_COOKIE_NAME = "session_id"

SESSION_COOKIE_SECURE = False  # -> True on HTTPS/production

SESSION_COOKIE_SAMESITE = "Lax"

# how many seconds of remaining time should be considered "needing extension"?
# if None, we'll extend it on every request (not recommended for heavily loaded systems)
SESSION_REFRESH_THRESHOLD = 60 * 15

# Stripe Settings
STRIPE_TEST_MODE = True
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'pk_test_51SDnMDHyBFLETxWaBIxoOc7biRTQFk8WxkL8MUZx5jpGpU4juUDydi3VXNXj3D5fQ3dLJktaPv1EVZrIbAZt6L4v00cTeXyY0Y')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
# Currency settings
DEFAULT_CURRENCY = 'usd'

if DEBUG:
    # The Stripe CLI's Secret for Local Testing
    STRIPE_WEBHOOK_SECRET = 'whsec_eaa38b9baeaa0972d8edbe87962390586f07ba2fa1673122e6529b54cad5143f'
else:
    # A secret from the Stripe production dashboard
    STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_2A09eN4lrR5NFAs9gINGxuokKgMMd0sD')
